# Generated by Django 5.1.2 on 2024-10-26 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '07' or '01' and be exactly 10 digits.", regex='^(07|01)\\d{8}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
